export const dataTypes = {
  sessions: "orch/sessions",
  speakers: "orch/presenters",
  posters: "orch/posters",
  showcaseSessions: "orch/showcases",
  exhibitors: "exhibitors",
  virtualBooths: "vbooths",
  faqs: "cms/faq",
  hero: "cms/hero-banners",
  horizontalBanner: "cms/horizontal-banners",
  towerBanner: "cms/tower-banners",
  notifications: "cms/notification",
  topNav: "cms/top-navigation",
  footerData: "cms/footer-navigation",
  homepageTiles: "cms/homepage-tiles",
  siteConfig: "cms/site-config",
  loginForm: "cms/auth",
  addChatUserToChannel: "/addChatUserToChannel",
  chatLivestream: "chat/livestream",
  retrieveBannedByList: "/retrieveBannedByList",
  leaderBoard: "leaderboards",
  attendeeLeaderBoards: "leaderboards/attendee",
  cmsLeaderBoard: "cms/leaderboard",
  favorites: "account/favorites",
  schedule: "account/schedule",
  accountProfile: "account/profile",
  accountBlock: "account/block",
  accountMute: "account/mute",
  webinars: "meetings/showcases",
  meetingAttendees: "meeting/attendees",
  meetingsJoinTokens: "meetings/joinTokens",
  meetingsEnd: "meetings/end",
  blockSingleMeeting: "meeting/block",
  meetings: "meetings",
  singleMeeting: "meeting",
  meetingAttendeeAccept: "meeting/attendeeAccept",
  meetingAttendeeDecline: "meeting/attendeeDecline",
  meetingsBatch: "meetings/batch",
  meetingAttendeeBatch: "meeting/attendee/batch",
  accountNotifications: "notifications/all",
  notificationsMarkRead: "notifications/markRead",
  guestProfile: "ACCOUNT/profile",
  networkSettings: "management/configurations",
  profileConfigurations: "management/permissions",
  surveys: "cms/surveys",
  accountGuestProfile: "account/guest/profile",
  accountGuestStatus: "account/guest/status",
};

export const DevicePermissionStatus = {
  UNSET: "UNSET",
  IN_PROGRESS: "IN_PROGRESS",
  GRANTED: "GRANTED",
  DENIED: "DENIED",
};
