export const SET_FILTERED_DATA = "SET_FILTERED_DATA";
export const SET_FULL_LIST = "SET_FULL_LIST";
export const NON_CONCATENATING_FILTER = "FILTER_DATA";
export const FILTER_DATA_BY_VALUE = "FILTER_DATA_BY_VALUE";
export const SET_FILTER_DATA_BY_VALUE_TO_ACTIVE =
  "SET_FILTER_DATA_BY_VALUE_TO_ACTIVE";
export const EMPTY_FILTERED_DATA = "EMPTY_FILTERED_DATA";
export const SET_FUZZY_SEARCH_RESULTS = "SET_FUZZY_SEARCH_RESULTS";
export const SET_TIMEZONE_FILTERS = "SET_TIMEZONE_FILTERS";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const EMPTY_SEARCH = "EMPTY_SEARCH";
export const IS_SEARCHING = "IS_SEARCHING";
export const SET_ACTIVE_FILTER_LIST = "SET_ACTIVE_FILTER_LIST";
export const UPDATE_FULL_LIST = "UPDATE_FULL_LIST";
export const REFILTER_DATA = "REFILTER_DATA";
export const ATTENDEE_FILTER_DATA_BY_VALUE = "ATTENDEE_FILTER_DATA_BY_VALUE";
export const SET_BREADCRUMB_LABEL_AND_URL = "SET_BREADCRUMB_LABEL_AND_URL";
