// import moment from "moment-timezone";

export const dummyData = [
  {
    Description:
      "These tech giants have fundamentally changed the landscape of content production. Our experts will walk you though this new frontier and give you the tools to succeed. ",
    EventId: 2898,
    EventRoom: {
      RoomId: 1149370,
      RoomName: "Room C2",
      DisplayName: "Room C2",
    },
    InteractionKey: null,
    IsDeleted: false,
    sessionCustom1:
      "Millennials and Gen Z don't watch TV on TV anymore. Learn how to engage them and create compelling content that can be viewed on YouTube Live, Twitch, Facebook Live, and Instagram Live, as well as on their mobile devices.",
    sessionCustom2: null,
    sessionVideoSource: "ls_embed_1588356975,9094134",
    sessionCustom4: null,
    sessionCustom5: null,
    sessionCustom6: null,
    sessionEnd: "2021-08-06T23:59:00",
    sessionId: 153377451,
    sessionName:
      "Excite your audience with professionally produced content and graphics II",
    sessionStart: "2021-08-11T10:42:00",
    sessionTrack: "Distribution",
    sessionType: "Livestream",
    active: false,
    iFrameId: "ls_embed_1588356975",
    streamId: "9094134",
    companyName: "Disney",
    host: "Tyra Banks",
  },
  {
    Description:
      "These tech giants have fundamentally changed the landscape of content production. Our experts will walk you though this new frontier and give you the tools to succeed. ",
    EventId: 2898,
    EventRoom: {
      RoomId: 1149370,
      RoomName: "Room C2",
      DisplayName: "Room C2",
    },
    InteractionKey: null,
    IsDeleted: false,
    sessionCustom1:
      "Millennials and Gen Z don't watch TV on TV anymore. Learn how to engage them and create compelling content that can be viewed on YouTube Live, Twitch, Facebook Live, and Instagram Live, as well as on their mobile devices.",
    sessionCustom2: null,
    sessionVideoSource: "ls_embed_1588356975,9094134",
    sessionCustom4: null,
    sessionCustom5: null,
    sessionCustom6: null,
    sessionEnd: "2021-08-06T23:59:00",
    sessionId: 153377452,
    sessionName:
      "How YouTube, Twitch, Facebook and Instagram Live change your content production",
    sessionStart: "2021-08-11T10:42:00",
    sessionTrack: "Distribution",
    sessionType: "Livestream",
    active: true,
    iFrameId: "ls_embed_1588356975",
    streamId: "9094134",
    companyName: "Anyfest",
    host: "Ryan Secrest",
  },
  {
    Description:
      "These tech giants have fundamentally changed the landscape of content production. Our experts will walk you though this new frontier and give you the tools to succeed. ",
    EventId: 2898,
    EventRoom: {
      RoomId: 1149370,
      RoomName: "Room C2",
      DisplayName: "Room C2",
    },
    InteractionKey: null,
    IsDeleted: false,
    sessionCustom1:
      "Millennials and Gen Z don't watch TV on TV anymore. Learn how to engage them and create compelling content that can be viewed on YouTube Live, Twitch, Facebook Live, and Instagram Live, as well as on their mobile devices.",
    sessionCustom2: null,
    sessionVideoSource: "ls_embed_1588356975,9094134",
    sessionCustom4: null,
    sessionCustom5: null,
    sessionCustom6: null,
    sessionEnd: "2021-08-06T23:59:00",
    sessionId: 153377453,
    sessionName:
      "Why you need more than a webcam and smartphone for your webcast II",
    sessionStart: "2021-08-11T10:43:00",
    sessionTrack: "Distribution",
    sessionType: "Livestream",
    active: true,
    iFrameId: "ls_embed_1588356975",
    streamId: "9094134",
    companyName: "Anyfest",
    host: "Walter Mitty",
  },
  {
    Description:
      "These tech giants have fundamentally changed the landscape of content production. Our experts will walk you though this new frontier and give you the tools to succeed. ",
    EventId: 2898,
    EventRoom: {
      RoomId: 1149370,
      RoomName: "Room C2",
      DisplayName: "Room C2",
    },
    InteractionKey: null,
    IsDeleted: false,
    sessionCustom1:
      "Millennials and Gen Z don't watch TV on TV anymore. Learn how to engage them and create compelling content that can be viewed on YouTube Live, Twitch, Facebook Live, and Instagram Live, as well as on their mobile devices.",
    sessionCustom2: null,
    sessionVideoSource: "ls_embed_1588356975,9094134",
    sessionCustom4: null,
    sessionCustom5: null,
    sessionCustom6: null,
    sessionEnd: "2021-12-21T23:59:00",
    sessionId: 153377454,
    sessionName: "The streaming video codec wars are just warming up",
    sessionStart: "2021-12-21T23:00:00",
    sessionTrack: "Distribution",
    sessionType: "Livestream",
    active: false,
    iFrameId: "ls_embed_1588356975",
    streamId: "9094134",
    companyName: "General Electric",
    host: "Amazon",
  },
];

// const utcTime = (time) => {
//   return moment.tz(time, ConfigService.runValues.momentTimezone).utc();
// };

export const dummyCal = [
  {
    sessionId: 19759887,
    eventId: 2972,
    clientSessionId: "1121",
    sessionName:
      "Connecting your virtual show floor with your IRL show floor II",
    description:
      "Creating a virtual show floor shouldn't just be re-creating your real-life booth on a web page. Discover how to amplify your expensive show floor booth into a digital experience that can excite potential customers and deliver a compelling message to the media and other stakeholders. Get best practices on what content you need to deliver online as well as what user experience modern, digitally savvy audiences demand.",
    sessionTrack: "Tradeshow",
    sessionStart: "2021-12-11T16:01:00",
    sessionEnd: "2021-12-11T18:58:00",
    sessionCustom1: "",
    sessionCustom2: null,
    sessionCustom3: "",
    sessionCustom4: "",
    sessionCustom5: null,
    sessionCustom6: null,
    interactionKey: "5m0qxfbt",
    sessionVideoSource: "ls_embed_1588356975,9094134",
    sessionSurveyLink: "https://www.surveymonkey.com/r/CYSSSXB",
    sessionExternalLink:
      "https://www.freeman.com/solutions/by-expertise/digital",
    sessionCmelink: "https://www.merriam-webster.com/dictionary/CME",
    secondaryTrack: "Exhibitor",
    keywords: "Booth, Virtual",
    groupMeetingLink: null,
    featuredSession: false,
    eventRoom: {
      roomId: 1512765,
      roomName: "Room C",
      displayName: "Room C",
    },
    moderatorFiles: null,
    sessionType: {
      sessionTypeId: 1088384,
      sessionTypeName: "Livestream",
    },
  },
  {
    sessionId: 19759887,
    eventId: 2972,
    clientSessionId: "1121",
    sessionName:
      "Connecting your virtual show floor with your IRL show floor II",
    description:
      "Creating a virtual show floor shouldn't just be re-creating your real-life booth on a web page. Discover how to amplify your expensive show floor booth into a digital experience that can excite potential customers and deliver a compelling message to the media and other stakeholders. Get best practices on what content you need to deliver online as well as what user experience modern, digitally savvy audiences demand.",
    sessionTrack: "Tradeshow",
    sessionStart: "2021-12-11T12:01:00",
    sessionEnd: "2021-12-11T12:58:00",
    sessionCustom1: "",
    sessionCustom2: null,
    sessionCustom3: "",
    sessionCustom4: "",
    sessionCustom5: null,
    sessionCustom6: null,
    interactionKey: "5m0qxfbt",
    sessionVideoSource: "ls_embed_1588356975,9094134",
    sessionSurveyLink: "https://www.surveymonkey.com/r/CYSSSXB",
    sessionExternalLink:
      "https://www.freeman.com/solutions/by-expertise/digital",
    sessionCmelink: "https://www.merriam-webster.com/dictionary/CME",
    secondaryTrack: "Exhibitor",
    keywords: "Booth, Virtual",
    groupMeetingLink: null,
    featuredSession: false,
    eventRoom: {
      roomId: 1512765,
      roomName: "Room C",
      displayName: "Room C",
    },
    moderatorFiles: null,
    sessionType: {
      sessionTypeId: 1088384,
      sessionTypeName: "Livestream",
    },
  },
  {
    sessionId: 19759887,
    eventId: 2972,
    clientSessionId: "1121",
    sessionName:
      "Connecting your virtual show floor with your IRL show floor II",
    description:
      "Creating a virtual show floor shouldn't just be re-creating your real-life booth on a web page. Discover how to amplify your expensive show floor booth into a digital experience that can excite potential customers and deliver a compelling message to the media and other stakeholders. Get best practices on what content you need to deliver online as well as what user experience modern, digitally savvy audiences demand.",
    sessionTrack: "Tradeshow",
    sessionStart: "2021-12-12T09:01:00",
    sessionEnd: "2021-12-12T12:58:00",
    sessionCustom1: "",
    sessionCustom2: null,
    sessionCustom3: "",
    sessionCustom4: "",
    sessionCustom5: null,
    sessionCustom6: null,
    interactionKey: "5m0qxfbt",
    sessionVideoSource: "ls_embed_1588356975,9094134",
    sessionSurveyLink: "https://www.surveymonkey.com/r/CYSSSXB",
    sessionExternalLink:
      "https://www.freeman.com/solutions/by-expertise/digital",
    sessionCmelink: "https://www.merriam-webster.com/dictionary/CME",
    secondaryTrack: "Exhibitor",
    keywords: "Booth, Virtual",
    groupMeetingLink: null,
    featuredSession: false,
    eventRoom: {
      roomId: 1512765,
      roomName: "Room C",
      displayName: "Room C",
    },
    moderatorFiles: null,
    sessionType: {
      sessionTypeId: 1088384,
      sessionTypeName: "Livestream",
    },
  },
  {
    sessionId: 19759887,
    eventId: 2972,
    clientSessionId: "1121",
    sessionName:
      "Connecting your virtual show floor with your IRL show floor II",
    description:
      "Creating a virtual show floor shouldn't just be re-creating your real-life booth on a web page. Discover how to amplify your expensive show floor booth into a digital experience that can excite potential customers and deliver a compelling message to the media and other stakeholders. Get best practices on what content you need to deliver online as well as what user experience modern, digitally savvy audiences demand.",
    sessionTrack: "Tradeshow",
    sessionStart: "2021-12-10T16:01:00",
    sessionEnd: "2021-12-10T22:58:00",
    sessionCustom1: "",
    sessionCustom2: null,
    sessionCustom3: "",
    sessionCustom4: "",
    sessionCustom5: null,
    sessionCustom6: null,
    interactionKey: "5m0qxfbt",
    sessionVideoSource: "ls_embed_1588356975,9094134",
    sessionSurveyLink: "https://www.surveymonkey.com/r/CYSSSXB",
    sessionExternalLink:
      "https://www.freeman.com/solutions/by-expertise/digital",
    sessionCmelink: "https://www.merriam-webster.com/dictionary/CME",
    secondaryTrack: "Exhibitor",
    keywords: "Booth, Virtual",
    groupMeetingLink: null,
    featuredSession: false,
    eventRoom: {
      roomId: 1512765,
      roomName: "Room C",
      displayName: "Room C",
    },
    moderatorFiles: null,
    sessionType: {
      sessionTypeId: 1088384,
      sessionTypeName: "Livestream",
    },
  },
  {
    sessionId: 19759887,
    eventId: 2972,
    clientSessionId: "1121",
    sessionName:
      "Connecting your virtual show floor with your IRL show floor II",
    description:
      "Creating a virtual show floor shouldn't just be re-creating your real-life booth on a web page. Discover how to amplify your expensive show floor booth into a digital experience that can excite potential customers and deliver a compelling message to the media and other stakeholders. Get best practices on what content you need to deliver online as well as what user experience modern, digitally savvy audiences demand.",
    sessionTrack: "Tradeshow",
    sessionStart: "2021-12-11T12:01:00",
    sessionEnd: "2021-12-11T18:58:00",
    sessionCustom1: "",
    sessionCustom2: null,
    sessionCustom3: "",
    sessionCustom4: "",
    sessionCustom5: null,
    sessionCustom6: null,
    interactionKey: "5m0qxfbt",
    sessionVideoSource: "ls_embed_1588356975,9094134",
    sessionSurveyLink: "https://www.surveymonkey.com/r/CYSSSXB",
    sessionExternalLink:
      "https://www.freeman.com/solutions/by-expertise/digital",
    sessionCmelink: "https://www.merriam-webster.com/dictionary/CME",
    secondaryTrack: "Exhibitor",
    keywords: "Booth, Virtual",
    groupMeetingLink: null,
    featuredSession: false,
    eventRoom: {
      roomId: 1512765,
      roomName: "Room C",
      displayName: "Room C",
    },
    moderatorFiles: null,
    sessionType: {
      sessionTypeId: 1088384,
      sessionTypeName: "Livestream",
    },
  },
];

export const dummyRoom = [
  {
    room: "Other",
    title: "Other",
  },
];
