const mockSessionDataNoSpeakers = {
  sessionId: 19759859,
  eventId: 2972,
  sponsorId: 846830,
  clientSessionId: "101",
  sessionName:
    "Excite your audience with professionally produced content and graphics",
  description:
    "Learn how to take a standard content package and craft it into a tool for boosting audience engagement.",
  sessionTrack: "Content",
  isDeleted: false,
  sessionStart: "2022-01-04T06:01:00",
  sessionEnd: "2022-01-04T20:45:00",
  sessionCustom1: "",
  sessionCustom2: null,
  sessionCustom3: "",
  sessionCustom4: "2021-10-26T10:00:00",
  sessionCustom5: null,
  sessionCustom6: null,
  interactionKey: "esadi7qo",
  sessionVideoSource: "ibm_24121036",
  sessionSurveyLink: "cme-survey",
  sessionExternalLink: "https://www.freeman.com/solutions/by-expertise/digital",
  sessionCmelink: "https://www.merriam-webster.com/dictionary/CME",
  secondaryTrack: "Virtual Events",
  keywords: "Virtual, Event, Tradeshow",
  groupMeetingLink: null,
  featuredSession: true,
  sessionFormat: {
    sessionFormatId: 1,
    sessionFormatName: "RoomInPerson",
  },
  sessionFormatId: 1,
  eventRoom: {
    roomId: 1512767,
    roomName: "Room A1",
    displayName: "Room A1",
  },
  moderators: [
    {
      username: "80dd4541c2a3ecabc7f4af502a7c5be3ee59eb2f",
      email: "80dd4541c2a3ecabc7f4af502a7c5be3ee59eb2f",
      firstName: "Valéry",
      middleName: null,
      lastName: "Giscard d'Estaing",
      suffix: "Valéry",
      degree: "Valéry",
      organization: "Valéry",
      isVip: false,
      userBioText: null,
      headShotUrl:
        "https://orchoepfiles.blob.core.windows.net/profile-photos/oepproduct2021%2Fjohnsmith%40email.non.jpg?1614981488959",
      disclosureText:
        '<p class="MsoNormal"><span style="font-weight: bolder;">2010-2015 - Lorem ipsum dolor sit<o:p></o:p></span></p><p class="MsoNormal">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.<o:p></o:p></p><p class="MsoNormal"><span style="font-weight: bolder;">2015-2020- deserunt mollit anim id est laborum.<o:p></o:p></span></p><p class="MsoNormal">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>',
      eventUserCustom1: "Valéry",
      eventUserCustom2: "Valéry",
      eventUserCustom3: "Valéry",
      eventUserCustom4: "Valéry",
      eventUserCustom5: "Valéry",
      preferredName: "Valéry",
      title: "French NameValéry",
      city: "Valéry",
      state: "Valéry",
      country: "Valéry",
      userUrl: "",
      prefix: "Valéry",
      socialMediaTypes: null,
      eventUserId: "e6086a3a-1104-4c24-85c7-eea1463d464b",
    },
  ],
  moderatorFiles: null,
  subSessions: [
    {
      clientSubSessionId: "1002",
      subSessionId: 25584050,
      eventId: 2972,
      subSessionName: "Introduction: The Changing Face of Content",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
      startTime: "2022-01-04T06:01:00",
      endTime: "2022-01-04T20:45:00",
      isDeleted: false,
      subSessionCustom1: "",
      subSessionCustom2: null,
      subSessionCustom3: "",
      subSessionCustom4: null,
      subSessionCustom5: null,
      subSessionCustom6: null,
      subSessionType: "Workshop",
      subSessionOrder: 1,
      subSessionVideoSource: null,
      subSurveyUrl: null,
      subExternalUrl: null,
      subInteractionKey: null,
      presentationFiles: [
        {
          presentationFileId: 40168850,
          fileName: "8.pdf",
          filePath:
            "EventFiles\\oepproduct2021\\PresentationFiles\\Uploads\\19759859\\25584050\\8.pdf",
          isHandOutFile: false,
          isDeleted: false,
          dateCreated: "0001-01-01T00:00:00",
          isStartupFile: false,
          status: "Pending",
        },
      ],
      presenters: null,
      sessionId: 19759859,
      sessionName:
        "Excite your audience with professionally produced content and graphics",
      sessionType: {
        sessionTypeId: 1088384,
        sessionTypeName: "Livestream",
      },
      sessionTrack: "Content",
      sessionStart: "2022-01-04T06:01:00",
      sessionEnd: "2022-01-04T20:45:00",
    },
    {
      clientSubSessionId: "1003",
      subSessionId: 25584051,
      eventId: 2972,
      subSessionName: "5 Graphic Design Strategies That Will Win Over Viewers",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
      startTime: "2022-01-04T06:01:00",
      endTime: "2022-01-04T20:45:00",
      isDeleted: false,
      subSessionCustom1:
        "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. You’re on your own. And you know what you know. And you are the one who’ll decide where to go.",
      subSessionCustom2: null,
      subSessionCustom3: "",
      subSessionCustom4: null,
      subSessionCustom5: null,
      subSessionCustom6: null,
      subSessionType: "Keynote",
      subSessionOrder: 1,
      subSessionVideoSource: null,
      subSurveyUrl: null,
      subExternalUrl: null,
      subInteractionKey: null,
      presentationFiles: null,
      presenters: null,
      sessionId: 19759859,
      sessionName:
        "Excite your audience with professionally produced content and graphics",
      sessionType: {
        sessionTypeId: 1088384,
        sessionTypeName: "Livestream",
      },
      sessionTrack: "Content",
      sessionStart: "2022-01-04T06:01:00",
      sessionEnd: "2022-01-04T20:45:00",
    },
  ],
  sessionType: {
    sessionTypeId: 1088384,
    sessionTypeName: "Livestream",
  },
};

export default mockSessionDataNoSpeakers;
