export const SET_CHANNELS = "SET_CHANNELS";
export const SET_CHAT_USER_FLAG = "SET_CHAT_USER_FLAG";
export const SET_CHAT_CLIENT = "SET_CHAT_CLIENT";
export const RESET_CHANNEL_LIST = "RESET_CHANNEL_LIST";
export const CHAT_TOKEN = "CHAT_TOKEN";
export const CHAT_LOGOUT = "CHAT_LOGOUT";
export const CHAT_BOTOPEN = "CHAT_BOTOPEN";
export const CHAT_UNREAD_COUNT = "CHAT_UNREAD_COUNT";
