export const SET_ROSTER_MAPPING = "SET_ROSTER_MAPPING";
export const UPDATE_ROSTER_MAPPING = "UPDATE_ROSTER_MAPPING";
export const CLEAR_MEETING = "CLEAR_MEETING";
export const SET_CURRENT_MEETING = "SET_CURRENT_MEETING";
export const SET_ATTENDEE_INFO = "SET_ATTENDEE_INFO";
